### ISSUE TITLE
Figure out and document what versions of Dart work

### ISSUE THREAD

**Issue by natebosch** [natebosch/dart_language_server#21]
From @jtmcdole:

I was unable to get lsc running on the stable 1.24.3 dart release (Ubuntu 16.04).  I would keep getting an error on autocomplete about 'not connected'.  Running the dart_language_server directly gave the following output:

```shell
 /usr/lib/dart/bin/dart /usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot --sdk /usr/lib/dart                                                        
{"event":"server.connected","params":{"version":"1.18.0","pid":20577,"sessionId":""}}
```

Updating to Dart 2.0 on the beta channel has errors and jump-to working.  Running the same command above yields:

```shell
{"event":"server.connected","params":{"version":"1.18.4","pid":27666,"sessionId":""}}
```

**Comment by natebosch** [comment]
I know there are potential issues around a version mismatch between when you `pub global activate` and when you run the server. I may need to expose some command line flags around which SDK and which analysis server to use.

@jtmcdole - I think you were able to get this working yourself? I'm curious whether https://github.com/natebosch/dart_language_server/issues/20 might also be a versioning thing...

**Comment by natebosch** [comment]
Yeah, I can see why this isn't working in the older SDKs. I should be able to fix it rather than forcing -dev SDK.

See https://github.com/natebosch/dart_language_server/issues/20#issuecomment-356428745

Will close this issue in favor of that one.

**Comment by jtmcdole** [comment]
sgtm
