### ISSUE TITLE
[BUG] codeLensProvider error

### ISSUE THREAD

**Issue by therealcisse** [natebosch/dart_language_server#28]
Hi,

dart_language_server sends 

```
"codeLensProvider": false
```

instead of 

```
"codeLensProvider": null
```
 to clients.

See: https://github.com/autozimu/LanguageClient-neovim/issues/335

for more details.

**Comment by natebosch** [comment]
Published `0.1.9+4`. Please upgrade and let me know if it is still an issue for you.

**Comment by therealcisse** [comment]
The error is gone but code completion doesn't seem to work.

**Comment by natebosch** [comment]
Are you seeing the same thing as described in https://github.com/natebosch/dart_language_server/issues/26 ?

**Comment by therealcisse** [comment]
FInaly works with an older version of LanguageClien-neovim.

**Comment by natebosch** [comment]
Sounds good. Definitely let me know if you find further evidence that there is a bug with the server implementation. The issue as filed was very actionable - thanks!
