### ISSUE TITLE
textDocumentSync.save should be a SaveOptions, not a boolean - backport to 0.1.5+3

### ISSUE THREAD

**Issue by natebosch** [natebosch/dart_language_server#48]

**Comment by natebosch** [comment]
ah, duplicate of #27

**Comment by natebosch** [comment]
Reopening to track applying this fix on an earlier version which is compatible with Dart 1.

**Comment by natebosch** [comment]
@reisub0 - I published this as 0.1.5+3 which is compatible with the Dart 1 SDKs - can you try the `pub global activate` one more time and see if you get this version?

**Comment by autolyticus** [comment]
Yes, I got the latest version and the error has been patched. Thanks!
