### ISSUE TITLE
optional new

### ISSUE THREAD

**Issue by ibarrick** [natebosch/dart_language_server#52]
I'm using vim-lsc with dart_language_server and flutter. How can I get the dart_language_server to no longer highlight usages of constructors that omit the `new` keyword? `new` is optional in Dart 2 and my code compiles and runs successfully.

**Comment by ibarrick** [comment]
Was using old dart sdk

**Comment by natebosch** [comment]
Sorry I didn't respond sooner - glad you were able to get it worked out.
