### ISSUE TITLE
Initialise server on any request for data, not only in textDocumentDidOpen

### ISSUE THREAD

**Issue by DanTup** [natebosch/dart_language_server#55]
Currently the server only sets analysis roots in textDocumentDidOpen. Visual Studio can send other events before this one (for example, it may request the symbols for a document before it's told us that it's open!).

I can't see anything in the spec forbidding this, so I think it may make sense that other requests should trigger the analysis roots being set too?

**Comment by natebosch** [comment]
Yeah I think it's probably sensible.

**Comment by natebosch** [comment]
Closing since I think the analysis server likely has this behavior and is now the canonical LSP server for Dart.
