### ISSUE TITLE
`executeCommandProvider` is not registered

### ISSUE THREAD

**Issue by chemzqm** [natebosch/dart_language_server#56]
There's 
```
        "executeCommandProvider": null,
```
in initialize options.
So client doesn't know the server could execute command, commands like `Organize imports` may not work.

**Comment by natebosch** [comment]
Looks like an easy fix.

https://github.com/natebosch/dart_language_server/pull/57

One question @chemzqm - am I correct in assuming those strings are shown to the user in whatever client you're using? I'm wondering if I should capitalize them...

**Comment by chemzqm** [comment]
There're two fields: `title` and `command` https://microsoft.github.io/language-server-protocol/specification#command, `title` is shown to user and `command` should be made to unique something like `_dart.organizeImport`.

`command` as identifier is provided in  ExecuteCommandOptions. You need to make sure it same as  `command` field in command from codeAction.

**Comment by natebosch** [comment]
The `Command` interface is used for responding to `textDocument/codeAction` requests, but the `ExecuteCommandOptions` interface in the capabilities has only a `commands: string[]`. I think this corresponds to the `command` parameter to `workspace/executeCommand`, but there is no way in the capabilities to provide a title...

I could co with something like `commands: ['dart.organizeImport', 'dart.sortMembers']` I suppose, but I'm not sure if any clients are going to want to show that to the user.

**Comment by chemzqm** [comment]
>  I think this corresponds to the command parameter to workspace/executeCommand

It is.

> but I'm not sure if any clients are going to want to show that to the user

It should not be shown to user, the `title` of` command` should be shown to user instead.
