### ISSUE TITLE
Add extract function/variable feature.

### ISSUE THREAD

**Issue by LinArcX** [natebosch/dart_language_server#60]
Hi.i'm looking for a solution that already exists in most ides today. __Extract function/variables__ via LSP-->codeactions. i ask this question this place too:
https://github.com/Microsoft/language-server-protocol/issues/662
It seems that server muse provide such feature via __CodeActionKinds__. Is there possible to implement this feature?

**Comment by natebosch** [comment]
Can you file this as a feature request at https://github.com/dart-lang/sdk/issues/ ?

The canonical LSP server for Dart is now the Dart analysis server.
