### ISSUE TITLE
LSP client lags compared with VSCode

### ISSUE THREAD

**Issue by netjune** [natebosch/dart_language_server#61]
I'm using emacs with eglot(a lsp client for emacs). With the same project and same completion position, emacs lags too much compared with VSCode.

I turn on their logs and see that their communication data differs too much.

VSCode: about 100 lines
eglot: about 10,000 lines

Log of VSCode:  http://119.37.194.6/upload/vscode_events.log
Log of eglot: http://119.37.194.6/upload/eglot_events.log

**Comment by natebosch** [comment]
The vast majority of the eglot log is a single very large completion response.

It looks like maybe the vscode logs are cut off? The line for the `"completion.results"` response is incomplete. It might be a lot longer if the entire thing was shown.

The only thing I can think of here to improve this would be to add support for the `isIncomplete` on autocomplete and not send all the suggestions at once. Though I wouldn't expect the list to be this huge in normal circumstances. Are you trying to autocomplete at the beginning of a word with no characters to give the server a hint on how to filter? Are you doing that in the VSCode case?

Can you configure eglot to not trigger a completion request until a trigger character is typed, or until at least a character or two have been typed in a word?

**Comment by netjune** [comment]
I am using eglot with company-mode(backend: company-capf). I set `company-minimum-prefix-length` to 2, which means completion request is triggered after at least two word-chars(for _counter: _c).  For vscode, the minimum length is 1.

I didn't notice that long lones in vscode's log are truncated. I don't know how to let vscode don't truncate them.

I tested them with the flutter's builtin demo project, the completion of the two were triggered at the same position and in the same file. With the same prefix("_c"), the delay before the first completion menu popups:

Vscode: about 200~400ms
eglot: about 2s

**Comment by netjune** [comment]
Was the completion result not for the prefix("_c") for eglot?

I test it again. For eglot, the completion menu only popups after at least two word-chars("_c").

**Comment by stradicat** [comment]
The scenario is the same for `lsp` in Emacs.

Response is as laggy.

(Still, a better alternative to Android Studio for Flutter projects)

**Comment by natebosch** [comment]
The canonical LSP server for Dart is now the analysis server shipped with the SDK. I think that implementation had a similar request which was solved in https://github.com/dart-lang/sdk/issues/37060

**Comment by stradicat** [comment]
Confirmed, new stable `1.7.8-hotfix.3` release fixed it.
It's now a pleasure to work with.
