### ISSUE TITLE
What unit does dart_language_server use in lsp ranges?

### ISSUE THREAD

**Issue by Avi-D-coder** [natebosch/dart_language_server#64]
Does this project use UTF-8, UTF-16, codepoint, or grapheme cluster indexes for lsp ranges?

I am conducting a [survey](https://github.com/Avi-D-coder/lsp-range-unit-survey) to inform the debate over what unit ranges should use in the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol).
The debate is occuring in [issue #376](https://github.com/Microsoft/language-server-protocol/issues/376).

**Comment by natebosch** [comment]
I think we use effectively `UTF-16` because that is what Dart strings are and I never paid very close attention...

The canonical LSP server for dart is now the Analysis Server that ships in the SDK.
